apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: backend-1
    app.kubernetes.io/component: backend-1
    app.kubernetes.io/instance: backend-1
  name: backend-1
  namespace: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      deployment: backend-1
  template:
    metadata:
      labels:
        deployment: backend-1
    spec:
      containers:
      - image: spring-boot-hello-world-imagestream:v1.0
        name: backend-1
        ports:
        - containerPort: 8080
          protocol: TCP
        env:
          - name: GREETING
            valueFrom:
             configMapKeyRef:
                name: backend-greeting
                key: greeting
        volumeMounts:
        - mountPath: /var/local/SP
          name: pvc-jars
      volumes:
      - name: pvc-jars
        persistentVolumeClaim:
          claimName: pvc-jars
