apiVersion: "v1"
kind: "LimitRange"
metadata:
  name: "spring-boot-hello-world-limits"
spec:
  limits:
    - type: "Pod"
      max:
        cpu: "2"
        memory: "500Mi"
      min:
        cpu: "200m"
        memory: "100Mi"
    - type: "Container"
      max:
        cpu: "2"
        memory: "450Mi"
      min:
        cpu: "100m"
        memory: "80Mi"
      default:
        cpu: "300m"
        memory: "350Mi"
      defaultRequest:
        cpu: "200m"
        memory: "350Mi"
      maxLimitRequestRatio:
        cpu: "10"
