apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-jars
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
  storageClassName: gp2
  volumeMode: Filesystem
