apiVersion: v1
kind: Service
metadata:
  labels:
    app: backend-1
    app.kubernetes.io/component: backend-1
    app.kubernetes.io/instance: backend-1
  name: backend-1
  namespace: backend
spec:
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    deployment: backend-1
  sessionAffinity: None
  type: ClusterIP
